# Generated by Django 4.0.4 on 2022-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alpha', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
