# Generated by Django 4.0.4 on 2022-05-21 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField(default=uuid.UUID('baca12ee-d3d6-46ea-ab4a-f2988f5a4784'), editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('official_name', models.CharField(max_length=100)),
                ('ISO_code', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('phone_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=10)),
            ],
        ),
    ]
