# Generated by Django 4.0.4 on 2022-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('alpha_2', models.CharField(max_length=3)),
                ('alpha_3', models.CharField(max_length=4)),
                ('numeric_code', models.CharField(max_length=5)),
                ('continent', models.CharField(max_length=20)),
                ('continent_code', models.CharField(max_length=5)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('flag', models.URLField()),
            ],
        ),
    ]
