# Generated by Django 4.0.4 on 2022-06-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_flag_country_flag_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_url',
        ),
    ]
